version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - cache

  cache:
    image: redis:latest
    ports:
      - '6379:6379'